### PR TITLE
Tutorials - client security

### PR DESCRIPTION
**Pull request by adamancini**

### CODE REVIEW

**Comment by BarryWilliams** [comment]
This is looking good. Thank you! 

A few things need to be updated.

* Follow the outline from the style guide. [See section 1 on the style guide](https://docs.google.com/document/d/1vDGggMPEyYSDOQ13uC34wv_eihPBOzaASXFl-Lc_D9U/edit#heading=h.700686qfa9kv)
* Please use a verb first in the 2FA section on number 2. [see section 3b on the style guide](https://docs.google.com/document/d/1vDGggMPEyYSDOQ13uC34wv_eihPBOzaASXFl-Lc_D9U/edit#heading=h.700686qfa9kv)
*  Fix missing images in 2FA and passwords section. [see preview](https://github.com/replicatedhq/kots.io/blob/tutorials-security/content/vendor/guides/vendor-portal/team/security.md)

As a favor, can you squash into one commit?

**Comment by adamancini** [comment]
> This is looking good. Thank you!
> 
> A few things need to be updated.
> 
> * Please follow the outline from the style guide. [See section 1 on the style guide](https://docs.google.com/document/d/1vDGggMPEyYSDOQ13uC34wv_eihPBOzaASXFl-Lc_D9U/edit#heading=h.700686qfa9kv)

talking on slack ^

> * Please use a verb first in the 2FA section on number 2. [see section 3c and 3d on the style guide](https://docs.google.com/document/d/1vDGggMPEyYSDOQ13uC34wv_eihPBOzaASXFl-Lc_D9U/edit#heading=h.700686qfa9kv)

fixt ^

> * Please fix missing images in 2FA and passwords section. [see preview](https://github.com/replicatedhq/kots.io/blob/tutorials-security/content/vendor/guides/vendor-portal/team/security.md)

fixt ^

**Comment by adamancini** [comment]
> As a favor, can you squash into one commit?

yeah we can squash and merge through the PR

**Comment by adamancini** [comment]
@BarryWilliams added missing images;  if you can review I'll squash and merge

**Pull request merged**
