### PR TITLE
Update helm-processing.md

### PR DESCRIPTION
**Pull request by dexhorthy**
This looks dope! I had a couple minor suggestions @jeffreygolden  (sorry I missed the boat on the initial PR 😂 )

### CODE REVIEW

**Comment by JustinN-Replicated** [comment]
lgtm

**Comment by paigecalvert** [comment]
Hi all, we're running through all the PRs with type::docs to make sure we pick up any diffs between kots.io and the new docs site. Looks like this one is still open from a couple months ago--is this still relevant?

**Comment by JustinN-Replicated** [comment]
@jeffreygolden could you take a review?
@paigecalvert AFAIK yes, still relevant. I took a quick read through.

**Review by jeffreygolden — DISMISSED** [review]

**Comment by paigecalvert** [comment]
Thank you @JustinN-Replicated and @jeffreygolden!

**Review by paigecalvert — DISMISSED** [review]

**Comment by JustinN-Replicated** [comment]
I'm not sure why checks were failing on [this one - Merge branch 'main' into helm-processing](https://github.com/replicatedhq/kots.io/pull/632/commits/77a07328b8b9e576a7808dfe4e2eee7da77a31a9) but I went ahead and found the blog and fixed the url. Can ya'll just review and approve real quick? No idea why the checks passed and it said merged but it didn't.

**Review by paigecalvert — APPROVED** [review]

**Pull request merged**
