### PR TITLE
[1.66.0] updated install docs for new --no-port-forward flag

### PR DESCRIPTION
**Pull request by cbodonnell**
Added the new `--no-port-forward` flag to the docs for the `install` command. The old `--port-forward` flag has been deprecated, so was removed from the docs.

### CODE REVIEW

**Review by ajp-io — APPROVED** [review]
Thanks for making this a draft. I'm going to approve in advance, and we'll merge when ready. Of course you might need a reapproval if we have to rebase the branch to merge, but oh well :)

**Review by jonquil2002 — APPROVED** [review]
lgtm

**Comment by jonquil2002** [comment]
@cbodonnell @ajp-io Please finalize and merge this as soon as you can. Didn't see a docs review requested, but I approved it anyway. We're switching over to the new docs repo tomorrow and want to close out all of the PRs here to do the final content diff. Thanks!

**Comment by ajp-io** [comment]
@jonquil2002 Thanks, we're waiting to merge this until 1.66 is released today.

**Comment by ajp-io** [comment]
Since we're now on the new docs site, I will port this to new repo and close this PR.

**Pull request closed without merging**
