### PR TITLE
Changed response to request and minor formatting

### PR DESCRIPTION
**Pull request by tdensmore**
Fixed a minor wording issue and changed some formatting for clarity.

### CODE REVIEW

**Comment by AmberAlston** [comment]
This is still open. Is it WIP, awaiting reviews, or completed?

**Comment by tdensmore** [comment]
This should be done. I am not sure if I have the LGTM approval to merge

**Comment by samantha-replicated** [comment]
You're good. The peer review was marked done 27 days ago. I'll merge it now :)

**Comment by tdensmore** [comment]
Thank you! I will delete my branch now.

**Pull request merged**
