### PR TITLE
Adding Kots Install Diagram

### PR DESCRIPTION
**Pull request by austinchambers**

### CODE REVIEW

**Comment by austinchambers** [comment]
image

**Comment by dexhorthy** [comment]
@austinchambers @marccampbell is this still something we want to try to get in?

**Comment by AmberAlston** [comment]
This is old enough it likely needs more iteration before we would consider merging it. Will follow up to see if it should just be closed at this point.

**Comment by AmberAlston** [comment]
Closing due to age of PR. Updated content will get submitted again in the future.

**Pull request closed without merging**
