### PR TITLE
41189 Updates screenshots

### PR DESCRIPTION
**Pull request by paigecalvert**
Updates the screenshots on the topics assigned to me in https://app.shortcut.com/replicated/story/41189/update-kots-io-docs-with-new-screenshots

Previews:
- Deploy an HA Cluster: https://deploy-preview-646--kotsio.netlify.app/vendor/guides/ha-guide/
- Package a Helm Chart: https://deploy-preview-646--kotsio.netlify.app/vendor/guides/helm-chart/
- Airgapped Cluster: https://deploy-preview-646--kotsio.netlify.app/vendor/guides/airgapped-cluster/
- Integrating Persistent Datastores: https://deploy-preview-646--kotsio.netlify.app/vendor/guides/persistent-datastores/
- Community Licenses: https://deploy-preview-646--kotsio.netlify.app/vendor/entitlements/community-licenses/

### CODE REVIEW

**Comment by JustinN-Replicated** [comment]
Under https://deploy-preview-646--kotsio.netlify.app/vendor/guides/ha-guide/#run-the-kots-installer--deploy-application it looks like the channels tab is different than the others (example: https://deploy-preview-646--kotsio.netlify.app/vendor/guides/airgapped-cluster/#airgap-bundle).

**Review by ajp-io — COMMENTED** [review]
- On the community licenses page, it says, "The license tile on the Dashboard page will be highlighted in yellow and contain the words 'Community Edition." But in the new screenshot, the tile isn't highlighted in yellow anymore, so the text should be updated to reflect the look of the new tile.
- deploy-config-change.png shows that you've already deployed the app with the config change. However, the flow indicates that you're being redirected here in order to apply the change, which means this version wouldn't be deployed yet. Not a dealbreaker or possibly even worth changing, but I'll note it as a difference from the old version at least.
- Justin noted this, but the vendor portal has changed appearances since the screenshots were taken, so your new vendor portal screenshots look different than the existing ones. Also not a dealbreaker, but something we could fix separately.
- In airgap-channels.png and others, did you decide to no longer highlight the app name in the app dropdown and not number the steps?
- In airgap-download-bundle.png, did you choose to not highlight "Download bundle" since the one highlighted in the previous screenshot was actually on a different line?
- In airgap-download-license.png, I think you meant to put a box around "Save Changes" rather than "Download license".

**Comment by ajp-io** [comment]
> * On the community licenses page, it says, "The license tile on the Dashboard page will be highlighted in yellow and contain the words 'Community Edition." But in the new screenshot, the tile isn't highlighted in yellow anymore, so the text should be updated to reflect the look of the new tile.

I updated the wording for this one if you want to confirm you approve of it.

**Comment by paigecalvert** [comment]
> * On the community licenses page, it says, "The license tile on the Dashboard page will be highlighted in yellow and contain the words 'Community Edition." But in the new screenshot, the tile isn't highlighted in yellow anymore, so the text should be updated to reflect the look of the new tile.
Fixed with your commit which I shall approve!

> * deploy-config-change.png shows that you've already deployed the app with the config change. However, the flow indicates that you're being redirected here in order to apply the change, which means this version wouldn't be deployed yet. Not a dealbreaker or possibly even worth changing, but I'll note it as a difference from the old version at least.
For sure, I've updated the screenshot and will commit the change shortly.

> * Justin noted this, but the vendor portal has changed appearances since the screenshots were taken, so your new vendor portal screenshots look different than the existing ones. Also not a dealbreaker, but something we could fix separately.
See https://replicated.slack.com/archives/C02TQTV9G2V/p1642785128309000?thread_ts=1642724061.282400&cid=C02TQTV9G2V for more context on this one

> * In airgap-channels.png and others, did you decide to no longer highlight the app name in the app dropdown and not number the steps?
Yeah, felt like the boxes were getting a little redundant. See https://replicated.slack.com/archives/C02TQTV9G2V/p1642785128309000?thread_ts=1642724061.282400&cid=C02TQTV9G2V for more context on this one

> * In airgap-download-bundle.png, did you choose to not highlight "Download bundle" since the one highlighted in the previous screenshot was actually on a different line?
Yeah, I did intentionally not highlight it because it felt odd pointing to the other version. I also figure it's pretty easy to find the Download bundle link in the UI itself, so the screenshot might not be providing additional value 

> * In airgap-download-license.png, I think you meant to put a box around "Save Changes" rather than "Download license".
I did! Thanks. Also adding this updated screenshot to my next commit

**Review by samantha-replicated — APPROVED** [review]
lgtm!

**Pull request merged**
