### PR TITLE
Release Notes 1.59.0

### PR DESCRIPTION
**Pull request by DanStough**

### CODE REVIEW

**Review by jeffreygolden — APPROVED** [review]

**Review by ajp-io — APPROVED** [review]

**Comment by jonquil2002** [comment]
@DanStough @JustinN-Replicated I made a commit with some direct edits. If you like them, please merge them. After you have a final version ready for review, please lmk and I'll to the approval. Thanks :)

**Comment by JustinN-Replicated** [comment]
Made a few changes for brevity and clarity (added links to help give context).

**Review by JustinN-Replicated — APPROVED** [review]
After latest commit we should be good to go.

**Review by paigecalvert — DISMISSED** [review]
Not sure if we needed another docs review, but just in case Jonquil has already signed off for the day: LGTM!

**Review by jonquil2002 — APPROVED** [review]

**Comment by jonquil2002** [comment]
@DanStough LGTM, but you have some check failures.

**Review by JustinN-Replicated — DISMISSED** [review]
I think good to go with latest changes

**Review by jonquil2002 — APPROVED** [review]

**Pull request merged**
