### PR TITLE
Added the 'placeholder' annotation to the reference guide.

### PR DESCRIPTION
**Pull request by tdensmore**
I have added the "placeholder" annotation to the reference documentation. 
Hopefully, I got the syntax correct, but I will need extra eyeballs on that (since I could not find any documentation on it).
This was requested by Wallaroo.

### CODE REVIEW

**Review by DanStough — APPROVED** [review]

**Comment by DanStough** [comment]
Might benefit from @JustinN-Replicated reviewing from the product perspective.

**Review by emosbaugh — COMMENTED** [review]
This doesnt feel like the right place to put this. Page title is `Optional Resources`.

**Comment by tdensmore** [comment]
> This doesn't feel like the right place to put this. Page title is `Optional Resources`.

I can definitely be convinced. Do you think the page title is wrong, or should I put my addition of the `placeholder` annotation somewhere else? I only put it here because a Vendor said they thought it belonged here with the other annotations that drive conditional resources.

**Comment by emosbaugh** [comment]
That and the intro paragraph detailing only when and exclude. I'll leave it to @JustinN-Replicated

**Comment by JustinN-Replicated** [comment]
It seems like this article describes 'Kubernetes Resource Inclusivity' so maybe that is a more accurate title? Having said that, in the previous documentation it didn't look like we included an example of when a resource should be included either; could the same database example be used (IE if a customer did want to use embedded)?

**Comment by tdensmore** [comment]
> It seems like this article describes 'Kubernetes Resource Inclusivity' so maybe that is a more accurate title? 

I just changed the filename to: `include-resources.md` and title to: "Including and Excluding Kubernetes Resources". does that work?

>Having said that, in the previous documentation it didn't look like we included an example of when a resource should be included either; could the same database example be used (IE if a customer did want to use embedded)?

I used the Ingress example because the `placeholder` annotation is currently mentioned [on that page](https://kots.io/vendor/packaging/ingress/). I wanted to keep everything consistent, but that might not be the best example to give? I'm open to changing it.

**Comment by JustinN-Replicated** [comment]
@tdensmore  The new page title works for me - I think it is a bit more accurate and succinct enough.  

I am always +1 for consistency; unsure if there is an example for including we could add as well though I think that's not a deal breaker in my opinion. LGTM and let Wallaroo give us feedback?

**Comment by tdensmore** [comment]
> @tdensmore The new page title works for me - I think it is a bit more accurate and succinct enough.
> 
> I am always +1 for consistency; unsure if there is an example for including we could add as well though I think that's not a deal breaker in my opinion. LGTM and let Wallaroo give us feedback?

Cool, thanks. I already ran this (on Slack) by Wallaroo and Mitch he approved and appreciated the improvements (will Slack you that thread) . If its okay - lets merge / release these changes and improve the example if needed?

**Review by JustinN-Replicated — APPROVED** [review]
LGTM

**Comment by tdensmore** [comment]
Merging despite failure, since the failure happened because that new page doesn't exist yet.

**Pull request merged**
